spring.application.name=fintracker

# Default profile
spring.profiles.active=prod

# Logging pattern (common)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] [%X{correlationId}] %logger - %msg%n