spring.application.name=fintracker

# ========== SERVER CONFIG ==========
server.port=8080

# ========== DATABASE CONFIG ==========
spring.datasource.url=jdbc:mysql://mysql-db:3306/fintracker_db
spring.datasource.username=root
spring.datasource.password=root
# spring.datasource.url=jdbc:mysql://localhost:3306/fintracker_db?useSSL=false&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== JPA / HIBERNATE CONFIG ==========
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.format_sql=true

# ========== JWT SECRET KEY ==========
jwt.secret=MyVerySecretKeyForJWTGenerationWhichIsLongEnough123!
jwt.expirationMs=86400000 

gemini.api.key=AIzaSyB-R-9gbVaMbO70FifNewivza7ntz-lRE0
gemini.model=gemini-2.5-flash
gemini.model.fallback=gemini-1.5-pro

logging.level.root=INFO
logging.level.com.fintracker_backend.fintracker=DEBUG


# Add this also
logging.level.org.springframework.aop=DEBUG
spring.aop.proxy-target-class=true

# ❌ Disable Hibernate SQL completely
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ❌ Turn OFF SQL logs
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] [%X{correlationId}] %logger - %msg%n
